import AppKit
import ApplicationServices
import SRCore

/// Captures the current selection (P-2, P-3, P-4).
///
/// Order of attack:
/// 1. Accessibility API: kAXSelectedTextAttribute on the focused element,
///    falling back to kAXSelectedTextRangeAttribute + value substring.
/// 2. Simulated ⌘C with full pasteboard snapshot/restore, verified via
///    changeCount. The user's clipboard is indistinguishable afterwards.
///
/// Concealed pasteboard items (org.nspasteboard.ConcealedType /
/// AutoGeneratedType) are refused: not spoken, cached, logged, or sent.
enum SelectionCapture {
    enum CaptureResult {
        case text(String, method: Method, sourceBundleID: String?)
        case empty
        case concealed          // P-4 refusal
        case accessibilityDenied
    }

    enum Method: String {
        case accessibility = "ax"
        case copyFallback = "copy"
    }

    static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    static func capture() -> CaptureResult {
        guard AXIsProcessTrusted() else { return .accessibilityDenied }

        switch accessibilitySelectedText() {
        case .concealed:
            SRLog.event("capture.concealed_refused", ["method": "ax"])
            return .concealed
        case .text(let text, let sourceBundleID)
            where !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty:
            SRLog.event("capture.ok", ["method": "ax", "chars": String(text.count)])
            return .text(text, method: .accessibility, sourceBundleID: sourceBundleID)
        case .text, .none:
            break
        }
        return copyFallback()
    }

    // MARK: - AX path (P-2)

    private enum AXSelection {
        case text(String, sourceBundleID: String?)
        case concealed
        case none
    }

    private static func accessibilitySelectedText() -> AXSelection {
        let systemWide = AXUIElementCreateSystemWide()
        var focusedRef: CFTypeRef?
        guard AXUIElementCopyAttributeValue(
            systemWide, kAXFocusedUIElementAttribute as CFString, &focusedRef) == .success,
            let focusedRaw = focusedRef,
            CFGetTypeID(focusedRaw) == AXUIElementGetTypeID()
        else { return .none }
        // CFTypeRef → AXUIElement after the type check above.
        let focused = focusedRaw as! AXUIElement
        let sourceBundleID = bundleID(for: focused)

        // Password fields and protected-content containers must be refused on
        // the AX path too. Pasteboard concealment types never run when AX can
        // read the selection directly.
        if isProtected(focused) { return .concealed }

        var selectedRef: CFTypeRef?
        if AXUIElementCopyAttributeValue(
            focused, kAXSelectedTextAttribute as CFString, &selectedRef) == .success,
           let text = selectedRef as? String, !text.isEmpty {
            return .text(text, sourceBundleID: sourceBundleID)
        }

        // Fallback: selected range + full value substring.
        var rangeRef: CFTypeRef?
        var valueRef: CFTypeRef?
        guard AXUIElementCopyAttributeValue(
                focused, kAXSelectedTextRangeAttribute as CFString, &rangeRef) == .success,
              let rangeRaw = rangeRef,
              CFGetTypeID(rangeRaw) == AXValueGetTypeID(),
              AXUIElementCopyAttributeValue(
                focused, kAXValueAttribute as CFString, &valueRef) == .success,
              let value = valueRef as? String
        else { return .none }

        var range = CFRange()
        guard AXValueGetValue(rangeRaw as! AXValue, .cfRange, &range),
              range.length > 0,
              range.location >= 0,
              range.location + range.length <= value.utf16.count
        else { return .none }

        let utf16 = Array(value.utf16)
        let slice = utf16[range.location..<(range.location + range.length)]
        return .text(
            String(utf16CodeUnits: Array(slice), count: slice.count),
            sourceBundleID: sourceBundleID)
    }

    private static func bundleID(for element: AXUIElement) -> String? {
        var pid: pid_t = 0
        guard AXUIElementGetPid(element, &pid) == .success else { return nil }
        return NSRunningApplication(processIdentifier: pid)?.bundleIdentifier
    }

    private static func isProtected(_ element: AXUIElement) -> Bool {
        var current: AXUIElement? = element
        // Check the focused element plus a few ancestors. Apps commonly put
        // AXContainsProtectedContent on a containing group rather than the
        // text field itself.
        for _ in 0..<6 {
            guard let candidate = current else { break }

            var protectedRef: CFTypeRef?
            if AXUIElementCopyAttributeValue(
                candidate,
                NSAccessibility.Attribute.containsProtectedContent.rawValue as CFString,
                &protectedRef) == .success,
               let protected = protectedRef as? NSNumber,
               protected.boolValue {
                return true
            }

            var subroleRef: CFTypeRef?
            if AXUIElementCopyAttributeValue(
                candidate, kAXSubroleAttribute as CFString, &subroleRef) == .success,
               let subrole = subroleRef as? String,
               subrole == NSAccessibility.Subrole.secureTextField.rawValue {
                return true
            }

            var parentRef: CFTypeRef?
            guard AXUIElementCopyAttributeValue(
                candidate, kAXParentAttribute as CFString, &parentRef) == .success,
                let parentRaw = parentRef,
                CFGetTypeID(parentRaw) == AXUIElementGetTypeID()
            else { break }
            current = (parentRaw as! AXUIElement)
        }
        return false
    }

    // MARK: - ⌘C fallback (P-3, P-4)

    private struct PasteboardSnapshot {
        let items: [[NSPasteboard.PasteboardType: Data]]

        init(_ pasteboard: NSPasteboard) {
            items = (pasteboard.pasteboardItems ?? []).map { item in
                var record: [NSPasteboard.PasteboardType: Data] = [:]
                for type in item.types {
                    if let data = item.data(forType: type) {
                        record[type] = data
                    }
                }
                return record
            }
        }

        func restore(to pasteboard: NSPasteboard) {
            pasteboard.clearContents()
            let restored: [NSPasteboardItem] = items.map { record in
                let item = NSPasteboardItem()
                for (type, data) in record {
                    item.setData(data, forType: type)
                }
                return item
            }
            if !restored.isEmpty {
                pasteboard.writeObjects(restored)
            }
        }
    }

    private static func copyFallback() -> CaptureResult {
        let pasteboard = NSPasteboard.general
        let snapshot = PasteboardSnapshot(pasteboard)
        let baseline = pasteboard.changeCount
        let sourceBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        postCmdC()

        // Poll for the pasteboard to change (apps take 20–300 ms to service ⌘C).
        var waited: TimeInterval = 0
        // Some apps service the synthetic copy slowly. Wait through the full
        // ownership window before restoring; once restored, we cannot safely
        // distinguish a delayed synthetic copy from a real same-app copy.
        while pasteboard.changeCount == baseline && waited < 0.9 {
            Thread.sleep(forTimeInterval: 0.02)
            waited += 0.02
        }

        guard pasteboard.changeCount != baseline else {
            // Restore exactly once. Never infer ownership of a later change:
            // the user may copy a different value in the same application.
            snapshot.restore(to: pasteboard)
            SRLog.event("capture.empty", ["method": "copy"])
            return .empty
        }

        // Restore only while we still own the copied selection. If the user
        // copied something else concurrently, preserving their newer change is
        // safer than blindly overwriting it with the old snapshot.
        let selectionChangeCount = pasteboard.changeCount
        defer {
            if pasteboard.changeCount == selectionChangeCount {
                snapshot.restore(to: pasteboard)
            }
        }

        // P-4: refuse concealed content before reading the string.
        let typeStrings = (pasteboard.types ?? []).map(\.rawValue)
        if !concealedTypes.isDisjoint(with: typeStrings) {
            SRLog.event("capture.concealed_refused", [:])
            return .concealed
        }

        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            SRLog.event("capture.empty", ["method": "copy"])
            return .empty
        }
        SRLog.event("capture.ok", ["method": "copy", "chars": String(text.count)])
        return .text(text, method: .copyFallback, sourceBundleID: sourceBundleID)
    }

    private static func postCmdC() {
        let source = CGEventSource(stateID: .hidSystemState)
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: 8, keyDown: true)   // vk 8 = C
        keyDown?.flags = .maskCommand
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: 8, keyDown: false)
        keyUp?.flags = .maskCommand
        keyDown?.post(tap: .cgAnnotatedSessionEventTap)
        keyUp?.post(tap: .cgAnnotatedSessionEventTap)
    }

    /// Read the clipboard directly ("Speak clipboard" menu action).
    /// Applies the same concealed-content refusal.
    static func clipboardText() -> CaptureResult {
        let pasteboard = NSPasteboard.general
        let typeStrings = (pasteboard.types ?? []).map(\.rawValue)
        if !concealedTypes.isDisjoint(with: typeStrings) {
            SRLog.event("capture.concealed_refused", [:])
            return .concealed
        }
        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return .empty
        }
        return .text(
            text,
            method: .copyFallback,
            sourceBundleID: NSWorkspace.shared.frontmostApplication?.bundleIdentifier)
    }
}
