import AppKit
import ApplicationServices
import SRCore

/// Captures the current selection (P-2, P-3, P-4).
///
/// Order of attack:
/// 1. Accessibility API: kAXSelectedTextAttribute on the focused element,
///    falling back to kAXSelectedTextRangeAttribute + value substring.
/// 2. Simulated ⌘C with full pasteboard snapshot/restore, verified via
///    changeCount. The user's clipboard is indistinguishable afterwards.
///
/// Concealed pasteboard items (org.nspasteboard.ConcealedType /
/// AutoGeneratedType) are refused: not spoken, cached, logged, or sent.
enum SelectionCapture {
    enum CaptureResult {
        case text(String, method: Method)
        case empty
        case concealed          // P-4 refusal
        case accessibilityDenied
    }

    enum Method: String {
        case accessibility = "ax"
        case copyFallback = "copy"
    }

    static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    static func capture() -> CaptureResult {
        guard AXIsProcessTrusted() else { return .accessibilityDenied }

        if let text = accessibilitySelectedText(), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            SRLog.event("capture.ok", ["method": "ax", "chars": String(text.count)])
            return .text(text, method: .accessibility)
        }
        return copyFallback()
    }

    // MARK: - AX path (P-2)

    private static func accessibilitySelectedText() -> String? {
        let systemWide = AXUIElementCreateSystemWide()
        var focusedRef: CFTypeRef?
        guard AXUIElementCopyAttributeValue(
            systemWide, kAXFocusedUIElementAttribute as CFString, &focusedRef) == .success,
            let focusedRaw = focusedRef,
            CFGetTypeID(focusedRaw) == AXUIElementGetTypeID()
        else { return nil }
        // CFTypeRef → AXUIElement after the type check above.
        let focused = focusedRaw as! AXUIElement

        var selectedRef: CFTypeRef?
        if AXUIElementCopyAttributeValue(
            focused, kAXSelectedTextAttribute as CFString, &selectedRef) == .success,
           let text = selectedRef as? String, !text.isEmpty {
            return text
        }

        // Fallback: selected range + full value substring.
        var rangeRef: CFTypeRef?
        var valueRef: CFTypeRef?
        guard AXUIElementCopyAttributeValue(
                focused, kAXSelectedTextRangeAttribute as CFString, &rangeRef) == .success,
              let rangeRaw = rangeRef,
              CFGetTypeID(rangeRaw) == AXValueGetTypeID(),
              AXUIElementCopyAttributeValue(
                focused, kAXValueAttribute as CFString, &valueRef) == .success,
              let value = valueRef as? String
        else { return nil }

        var range = CFRange()
        guard AXValueGetValue(rangeRaw as! AXValue, .cfRange, &range),
              range.length > 0,
              range.location >= 0,
              range.location + range.length <= value.utf16.count
        else { return nil }

        let utf16 = Array(value.utf16)
        let slice = utf16[range.location..<(range.location + range.length)]
        return String(utf16CodeUnits: Array(slice), count: slice.count)
    }

    // MARK: - ⌘C fallback (P-3, P-4)

    private struct PasteboardSnapshot {
        let items: [[NSPasteboard.PasteboardType: Data]]

        init(_ pasteboard: NSPasteboard) {
            items = (pasteboard.pasteboardItems ?? []).map { item in
                var record: [NSPasteboard.PasteboardType: Data] = [:]
                for type in item.types {
                    if let data = item.data(forType: type) {
                        record[type] = data
                    }
                }
                return record
            }
        }

        func restore(to pasteboard: NSPasteboard) {
            pasteboard.clearContents()
            let restored: [NSPasteboardItem] = items.map { record in
                let item = NSPasteboardItem()
                for (type, data) in record {
                    item.setData(data, forType: type)
                }
                return item
            }
            if !restored.isEmpty {
                pasteboard.writeObjects(restored)
            }
        }
    }

    private static func copyFallback() -> CaptureResult {
        let pasteboard = NSPasteboard.general
        let snapshot = PasteboardSnapshot(pasteboard)
        let baseline = pasteboard.changeCount

        postCmdC()

        // Poll for the pasteboard to change (apps take 20–300 ms to service ⌘C).
        var waited: TimeInterval = 0
        while pasteboard.changeCount == baseline && waited < 0.6 {
            Thread.sleep(forTimeInterval: 0.02)
            waited += 0.02
        }

        defer {
            // P-3: restore within 300 ms of reading the selection.
            snapshot.restore(to: pasteboard)
        }

        guard pasteboard.changeCount != baseline else {
            SRLog.event("capture.empty", ["method": "copy"])
            return .empty
        }

        // P-4: refuse concealed content before reading the string.
        let typeStrings = (pasteboard.types ?? []).map(\.rawValue)
        if !concealedTypes.isDisjoint(with: typeStrings) {
            SRLog.event("capture.concealed_refused", [:])
            return .concealed
        }

        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            SRLog.event("capture.empty", ["method": "copy"])
            return .empty
        }
        SRLog.event("capture.ok", ["method": "copy", "chars": String(text.count)])
        return .text(text, method: .copyFallback)
    }

    private static func postCmdC() {
        let source = CGEventSource(stateID: .hidSystemState)
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: 8, keyDown: true)   // vk 8 = C
        keyDown?.flags = .maskCommand
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: 8, keyDown: false)
        keyUp?.flags = .maskCommand
        keyDown?.post(tap: .cgAnnotatedSessionEventTap)
        keyUp?.post(tap: .cgAnnotatedSessionEventTap)
    }

    /// Read the clipboard directly ("Speak clipboard" menu action).
    /// Applies the same concealed-content refusal.
    static func clipboardText() -> CaptureResult {
        let pasteboard = NSPasteboard.general
        let typeStrings = (pasteboard.types ?? []).map(\.rawValue)
        if !concealedTypes.isDisjoint(with: typeStrings) {
            SRLog.event("capture.concealed_refused", [:])
            return .concealed
        }
        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return .empty
        }
        return .text(text, method: .copyFallback)
    }
}
