import Testing
@testable import SRCore

/// T-4: golden-file parity against reference/normalize.py.
///
/// Fixtures live in fixtures/NN-name.in.txt with expected output in
/// NN-name.out.txt, generated by the reference implementation (ftfy
/// installed, pylatexenc absent — matching sr's documented deviations).
/// No Foundation import here — see FixtureLoader.swift.
@Suite struct NormalizerParityTests {
    /// Trim at most one trailing newline from both sides of the comparison.
    static func trimOneTrailingNewline(_ s: String) -> String {
        s.hasSuffix("\n") ? String(s.dropLast()) : s
    }

    /// Human-readable first-divergence report.
    static func firstDivergence(_ got: String, _ want: String) -> String {
        let g = Array(got.unicodeScalars)
        let w = Array(want.unicodeScalars)
        var i = 0
        while i < g.count && i < w.count && g[i] == w[i] { i += 1 }
        if i == g.count && i == w.count { return "identical" }
        func context(_ a: [Unicode.Scalar], _ at: Int) -> String {
            let lo = max(0, at - 40)
            let hi = min(a.count, at + 40)
            var out = ""
            for s in a[lo..<hi] {
                out += s == "\n" ? "\\n" : String(s)
            }
            return out
        }
        return """
        first divergence at scalar \(i):
          got:  …\(context(g, i))…
          want: …\(context(w, i))…
        """
    }

    @Test func fixturesExist() {
        #expect(FixtureLoader.names().count >= 25,
                "expected ≥25 fixtures, found \(FixtureLoader.names().count)")
    }

    @Test(arguments: FixtureLoader.names())
    func parity(fixture: String) {
        guard let pair = FixtureLoader.pair(named: fixture) else {
            Issue.record("fixture \(fixture) not found")
            return
        }
        let got = Self.trimOneTrailingNewline(Normalizer.normalize(pair.input))
        let want = Self.trimOneTrailingNewline(pair.expected)
        #expect(got == want, "\(fixture): \(Self.firstDivergence(got, want))")
    }

    @Test func frontendDetection() {
        func input(_ name: String) -> String {
            FixtureLoader.pair(named: name)?.input ?? ""
        }
        #expect(Normalizer.detectFrontend(input("01-latex-basic")) == .latex)
        #expect(Normalizer.detectFrontend(input("08-md-frontmatter")) == .markdown)
        #expect(Normalizer.detectFrontend(input("19-pdf-scinot")) == .pdf)
        // The reference also routes this one to pdf (footnote refs are not
        // high-confidence markdown signals) — detection must agree.
        #expect(Normalizer.detectFrontend(input("15-md-footnotes")) == .pdf)
    }
}
